---
# Playbook to setup workers

- hosts: workers
  roles:
    - get_host_facts
    - install_dependencies
    # - install_docker
    - install_apache_hadoop
    - install_apache_spark
    - configure_hdfs_yarn_cluster
    - setup_bashrc
  become: yes
  vars_files:
    - group_vars/node.yml
    - group_vars/hdfs.yml