---
# tasks file for get_hostname_and_ip
- name: Print current Ansible Host and User
  debug: 
    msg: "{{ inventory_hostname }} - {{ ansible_user }}"

- name: Read inventory file - Master
  debug: 
    msg: "Master: {{ item }}"
  loop: "{{ groups['master']}}"

- name: Read inventory file - Worker
  debug:
    msg: "Worker: {{ item }}"
  loop: "{{ groups['workers']}}"